services:
  wordpress:
    build:
      context: ./docker/koyeb-build
      dockerfile: Dockerfile.koyeb
    ports:
      - '8080:8080'
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: '0'
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    # Important: no volumes
