services:
  mysql:
    build:
      context: ./docker/mysql-build
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - path: .env
        required: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    command:
      - bash
      - -c
      - |
        elasticsearch-plugin install analysis-icu --batch && \
        /usr/local/bin/docker-entrypoint.sh

  wordpress:
    build:
      context: .
      dockerfile: docker/wordpress-build/Dockerfile
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost:8000' );
        define( 'WP_SITEURL', 'http://localhost:8000' );
        define( 'WP_ALLOW_MULTISITE', true );
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', 'localhost:8000' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 );
      EP_HOST: http://elasticsearch:9200
      WORDPRESS_SMTP_HOST: mailpit
      WORDPRESS_SMTP_PORT: 1025
      VIRTUAL_HOST: localhost
      WP_CLI_URL: http://localhost:8000
    env_file:
      - path: .env
        required: true
    volumes:
      - ./wordpress:/var/www/html
      - ./themes/:/var/www/html/wp-content/themes
      - ./plugins/:/var/www/html/wp-content/plugins

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mysql_data:
